name: 'Manage PDP Service'
description: 'Manages Permit.io PDP Docker container lifecycle with optimizations'

inputs:
  action:
    description: 'Action to perform (start|stop|health-check)'
    required: true
  permit-api-key:
    description: 'Permit.io API key (required for start action)'
    required: false
  snyk-token:
    description: 'Snyk token (optional)'
    required: false
  snyk-org-id:
    description: 'Snyk organization ID (optional)'
    required: false
  user-key:
    description: 'User key for Permit.io'
    required: false
  user-role:
    description: 'User role for Permit.io'
    required: false
  compose-file:
    description: 'Path to docker-compose file'
    required: false
    default: 'permit-gating/docker/docker-compose.gating.yml'
  health-check-url:
    description: 'URL for health checking'
    required: false
    default: 'http://localhost:7001/healthy'
  use-smart-caching:
    description: 'Use smart Docker image caching'
    required: false
    default: 'true'
  max-wait-time:
    description: 'Maximum wait time for health check (seconds)'
    required: false
    default: '120'

outputs:
  startup-time:
    description: 'Time taken for PDP to start (seconds)'
    value: ${{ steps.manage-pdp.outputs.startup-time }}
  pdp-status:
    description: 'Status of PDP service'
    value: ${{ steps.manage-pdp.outputs.pdp-status }}
  cache-used:
    description: 'Whether Docker cache was used'
    value: ${{ steps.manage-pdp.outputs.cache-used }}

runs:
  using: 'composite'
  steps:
    - name: Manage PDP Service
      id: manage-pdp
      shell: bash
      env:
        PERMIT_API_KEY: ${{ inputs.permit-api-key }}
        SNYK_TOKEN: ${{ inputs.snyk-token }}
        SNYK_ORG_ID: ${{ inputs.snyk-org-id }}
        USER_KEY: ${{ inputs.user-key }}
        USER_ROLE: ${{ inputs.user-role }}
      run: |
        ACTION="${{ inputs.action }}"
        COMPOSE_FILE="${{ inputs.compose-file }}"
        HEALTH_CHECK_URL="${{ inputs.health-check-url }}"
        MAX_WAIT="${{ inputs.max-wait-time }}"
        USE_SMART_CACHING="${{ inputs.use-smart-caching }}"
        
        case "$ACTION" in
          "start")
            echo "🚀 Starting PDP Service..."
            DOCKER_START_TIME=$(date +%s)
            
            # Create .env file for Docker Compose
            cat > .env << EOF
        PERMIT_API_KEY=$PERMIT_API_KEY
        SNYK_TOKEN=$SNYK_TOKEN
        SNYK_ORG_ID=$SNYK_ORG_ID
        USER_KEY=${USER_KEY}
        USER_ROLE=${USER_ROLE}
        EOF
            
            # Check for cached images if smart caching is enabled
            CACHE_USED="false"
            if [ "$USE_SMART_CACHING" = "true" ]; then
              echo "🔍 Checking cached images..."
              if docker image ls --format "table {{.Repository}}:{{.Tag}}\t{{.Size}}\t{{.CreatedSince}}" | grep -E "permitio/pdp-v2:latest"; then
                echo "✅ Found cached PDP image"
                CACHE_USED="true"
              else
                echo "📥 No cached image found, will pull fresh"
              fi
            fi
            
            # Pull images if needed
            echo "📥 Pulling PDP image if needed..."
            docker compose -f "$COMPOSE_FILE" pull --ignore-pull-failures
            
            # Start PDP service
            echo "🐳 Starting Safe Deployment Gate infrastructure..."
            echo "   ✅ PDP (Policy Decision Point): Required for authorization decisions"
            echo "   🚫 OPAL Server: Not needed - policies managed by Permit.io cloud"
            echo "   🚫 Redis: Not needed - no OPAL services required"
            echo ""
            
            docker compose -f "$COMPOSE_FILE" up -d
            
            # Verify service is running
            echo "📋 Active Safe Deployment Gate services:"
            docker compose -f "$COMPOSE_FILE" ps
            
            # Smart health checking with exponential backoff
            echo "🏥 Waiting for services to become healthy..."
            TOTAL_WAIT=0
            PDP_STATUS="starting"
            
            # Exponential backoff: 1s, 2s, 4s, 8s, 15s, 30s, then 30s intervals
            for WAIT_TIME in 1 2 4 8 15 30 30 30; do
              if curl -sf "$HEALTH_CHECK_URL" > /dev/null 2>&1; then
                echo "✅ PDP health endpoint ready after ${TOTAL_WAIT}s"
                PDP_STATUS="healthy"
                break
              elif [ $TOTAL_WAIT -ge $MAX_WAIT ]; then
                echo "❌ PDP failed to become ready after ${TOTAL_WAIT}s"
                echo "🔍 PDP Container logs:"
                docker compose -f "$COMPOSE_FILE" logs permit-pdp --tail=10
                PDP_STATUS="unhealthy"
                break
              else
                echo "⏳ PDP not ready yet, waiting ${WAIT_TIME}s... (total: ${TOTAL_WAIT}s)"
                sleep $WAIT_TIME
                TOTAL_WAIT=$((TOTAL_WAIT + WAIT_TIME))
              fi
            done
            
            # Calculate startup time
            DOCKER_END_TIME=$(date +%s)
            DOCKER_TOTAL_TIME=$((DOCKER_END_TIME - DOCKER_START_TIME))
            
            echo "⏱️ Docker startup completed in ${DOCKER_TOTAL_TIME}s"
            
            if [ "$USE_SMART_CACHING" = "true" ]; then
              echo "🚀 Performance optimizations applied:"
              echo "   ✅ PDP-only architecture (simplified from OPAL + Redis + Fetcher)"
              echo "   ✅ Smart image caching (skip downloads for existing images)"
              echo "   ✅ Exponential backoff health checking (vs fixed 30s wait)"
            fi
            
            # Verify PDP sync with cloud
            if [ "$PDP_STATUS" = "healthy" ]; then
              echo "Verifying PDP sync with Permit.io cloud..."
              for i in {1..20}; do
                response=$(curl -s -X POST http://localhost:7766/allowed \
                  -H "Content-Type: application/json" \
                  -H "Authorization: Bearer $PERMIT_API_KEY" \
                  -d '{"user":{"key":"sync-test","attributes":{"role":"test"}},"action":"test","resource":{"type":"deployment","key":"sync-test","attributes":{}}}' 2>/dev/null || echo "{}")
                
                if echo "$response" | grep -q '"synced":true'; then
                  echo "✓ PDP is fully synced with Permit.io cloud"
                  break
                elif [ $i -eq 20 ]; then
                  echo "⚠️ PDP sync verification timeout - proceeding anyway"
                else
                  echo "  Waiting for PDP to sync with cloud... ($i/20)"
                  sleep 3
                fi
              done
            fi
            
            echo "startup-time=$DOCKER_TOTAL_TIME" >> $GITHUB_OUTPUT
            echo "pdp-status=$PDP_STATUS" >> $GITHUB_OUTPUT
            echo "cache-used=$CACHE_USED" >> $GITHUB_OUTPUT
            ;;
            
          "stop")
            echo "🔽 Stopping PDP Service..."
            docker compose -f "$COMPOSE_FILE" down
            echo "✅ PDP service stopped"
            echo "pdp-status=stopped" >> $GITHUB_OUTPUT
            ;;
            
          "health-check")
            echo "🏥 Checking PDP health..."
            if curl -sf "$HEALTH_CHECK_URL" > /dev/null 2>&1; then
              echo "✅ PDP is healthy"
              echo "pdp-status=healthy" >> $GITHUB_OUTPUT
            else
              echo "❌ PDP is not healthy"
              echo "🔍 PDP Container status:"
              docker compose -f "$COMPOSE_FILE" ps
              echo "🔍 PDP Container logs:"
              docker compose -f "$COMPOSE_FILE" logs permit-pdp --tail=10
              echo "pdp-status=unhealthy" >> $GITHUB_OUTPUT
            fi
            ;;
            
          *)
            echo "❌ Invalid action: $ACTION"
            echo "   Valid actions: start, stop, health-check"
            exit 1
            ;;
        esac