name: "Snyk Scan"
description: "Runs Snyk security scan and reports vulnerabilities"

inputs:
  app-path:
    description: "Path of the project to scan"
    required: true
  snyk-token:
    description: "snyk token"
    required: true
  snyk-org:
    description: "snyk organization"
    required: true
  snyk-project-name:
    description: "snyk project name"
    required: true
  image-sha:
    description: "image-sha"
    required: true

runs:
  using: "composite"
  steps:

    - name: Install Snyk CLI
      shell: bash
      run: npm install -g snyk > /dev/null

    - name: Snyk Env Info
      shell: bash
      run: |
        echo "Snyk Scan Configuration:"
        echo "Project: ${{ inputs.snyk-project-name }}"
        echo "Image: myapp:${{ inputs.image-sha }}"

    - name: Run Snyk Scan (Container)
      shell: bash
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ inputs.snyk-token }}
      run: |
        cd ${{ inputs.app-path }}

        echo "Running container scan on myapp:${{ inputs.image-sha }}"

        snyk container test myapp:${{ inputs.image-sha }} \
          --file=Dockerfile \
          --org="${{ inputs.snyk-org }}" \
          --project-name="${{ inputs.snyk-project-name }}" \
          --json-file-output=snyk-report.json || true

        ls -lh snyk-report.json || echo "❌ snyk-report.json NOT GENERATED"

    - name: Snyk Gating
      shell: bash
      env:
        SNYK_TOKEN: ${{ inputs.snyk-token }}
        SNYK_ORG: ${{ inputs.snyk-org }}
        SNYK_PROJECT: ${{ inputs.snyk-project-name }}
      run: |
        python3 ./.github/actions/snyk-code-analysis/snyk_gating.py \
          --api-url "https://api.snyk.io" \
          --org-id "${SNYK_ORG}" \
          --project-name "${SNYK_PROJECT}" \
          --token "${SNYK_TOKEN}" \
          --threshold-file ./gating-configs/snyk_gating_thresholds.json \
          --report-file "${{ inputs.app-path }}/snyk-report.json"
