# ------------------------------------------------------------
# Composite Action: Snyk Scan
# Ejecuta un escaneo de seguridad usando Snyk CLI y genera un
# reporte JSON. También ejecuta la lógica de “gating” mediante
# un script Python para validar umbrales de seguridad.
# ------------------------------------------------------------
name: "Snyk Scan"
description: "Runs Snyk security scan and reports vulnerabilities"

# ------------------------------------------------------------
# Parámetros de entrada requeridos por la acción.
# Son provistos por el workflow que llame a este composite.
# ------------------------------------------------------------
inputs:
  app-path:
    description: "Path of the project to scan"
    required: true

  snyk-token:
    description: "Snyk authentication token"
    required: true

  snyk-org:
    description: "Snyk organization ID"
    required: true

  snyk-project-name:
    description: "Snyk project name"
    required: true

  image-sha:
    description: "Image / commit SHA used for tagging the scan"
    required: true

# ------------------------------------------------------------
# Definición del composite action
# ------------------------------------------------------------
runs:
  using: "composite"
  steps:

    # --------------------------------------------------------
    # Instala el CLI de Snyk globalmente vía npm
    # --------------------------------------------------------
    - name: Install Snyk CLI
      shell: bash
      run: npm install -g snyk > /dev/null

    # --------------------------------------------------------
    # Muestra información útil del entorno y configuración
    # --------------------------------------------------------
    - name: Snyk Env Info
      shell: bash
      run: |
        echo "Snyk Scan Configuration:"
        echo "Project: ${{ inputs.snyk-project-name }}"
        echo "Image: myapp:${{ inputs.image-sha }}"

    # --------------------------------------------------------
    # Ejecuta el escaneo del contenedor usando Snyk
    # Se genera un archivo JSON llamado `snyk-report.json`
    # continue-on-error: true -> No falla el job si Snyk detecta vulnerabilidades
    # --------------------------------------------------------
    - name: Run Snyk Scan (Container)
      shell: bash
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ inputs.snyk-token }}
      run: |
        cd ${{ inputs.app-path }}

        echo "Running container scan on myapp:${{ inputs.image-sha }}"

        snyk container test myapp:${{ inputs.image-sha }} \
          --file=Dockerfile \
          --org="${{ inputs.snyk-org }}" \
          --project-name="${{ inputs.snyk-project-name }}" \
          --json-file-output=snyk-report.json || true

        # Verificación del archivo generado
        ls -lh snyk-report.json || echo "❌ snyk-report.json NOT GENERATED"

    # --------------------------------------------------------
    # Ejecuta el proceso de Snyk Gating
    # Este script valida umbrales y “aprueba/reprueba” el escaneo
    # según reglas definidas en la config JSON.
    # --------------------------------------------------------
    - name: Snyk Gating
      shell: bash
      env:
        SNYK_TOKEN: ${{ inputs.snyk-token }}
        SNYK_ORG: ${{ inputs.snyk-org }}
        SNYK_PROJECT: ${{ inputs.snyk-project-name }}
      run: |
        python3 ./.github/actions/snyk-code-analysis/snyk_gating.py \
          --api-url "https://api.snyk.io" \
          --org-id "${SNYK_ORG}" \
          --project-name "${SNYK_PROJECT}" \
          --token "${SNYK_TOKEN}" \
          --threshold-file ./gating-configs/snyk_gating_thresholds.json \
          --report-file "${{ inputs.app-path }}/snyk-report.json"
