name: "Snyk Scan"
description: "Runs Snyk security scan and reports critical vulnerabilities"

inputs:
  app-path:
    description: "Path of the project to scan"
    required: true
  snyk-token:
    description: "snyk token"
    required: true
  snyk-org:
    description: "snyk organization"
    required: true
  snyk-project-name:
    description: "snyk project name"
    required: true

runs:
  using: "composite"
  steps:

    - name: Install Snyk CLI
      shell: bash
      run: npm install -g snyk > /dev/null

    - name: Snyk Env Info
      shell: bash
      run: |
        echo "Snyk Scan Configuration:"
        echo "App Path: ${{ inputs.app-path }}"
        echo "Snyk Organization: ${{ inputs.snyk-org }}"
        echo "Snyk Project Name: ${{ inputs.snyk-project-name }}"

    - name: Detect Tech Stack via Python
      shell: bash
      run: |
        cd ${{ inputs.app-path }}
        python3 scripts/detect_tech.py
        echo "Detected stack: $SNYK_STACK"

    - name: Resolve Snyk Command (Python)
      shell: bash
      run: |
        cd ${{ inputs.app-path }}
        python3 ./scripts/resolve_snyk_command.py
        echo "Resolved SNYK_CMD: $SNYK_CMD"

    # ------------------------------------------------------------------
    #  Snyk Scan (Docker / Code / SCA)
    # ------------------------------------------------------------------
    - name: Run Snyk Scan
      shell: bash
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ inputs.snyk-token }}
        IMAGE_TAG: ${{ env.IMAGE_TAG }}
      run: |
        cd ${{ inputs.app-path }}

        echo "Running scan for image: $IMAGE_TAG"

        $SNYK_CMD "$IMAGE_TAG" --file=Dockerfile \
          --org="${{ inputs.snyk-org }}" \
          --json-file-output=snyk-report.json || true

        ls -lh snyk-report.json || echo "❌ snyk-report.json NOT GENERATED"

    # ------------------------------------------------------------------
    #  Snyk Gating Phase
    # ------------------------------------------------------------------
    - name: Snyk Gating
      shell: bash
      env:
        SNYK_TOKEN: ${{ inputs.snyk-token }}
        SNYK_ORG: ${{ inputs.snyk-org }}
        SNYK_PROJECT: ${{ inputs.snyk-project-name }}
      run: |
        echo "Running Snyk gating check for project ${SNYK_PROJECT}..."

        python3 ./.github/actions/snyk-code-analysis/snyk_gating.py \
          --api-url "https://api.snyk.io" \
          --org-id "${SNYK_ORG}" \
          --project-name "${SNYK_PROJECT}" \
          --token "${SNYK_TOKEN}" \
          --threshold-file ./gating-configs/snyk_gating_thresholds.json \
          --report-file "${{ inputs.app-path }}/snyk-report.json"
