name: 'Process Test Results'
description: 'Processes unit test results and coverage data for quality analysis integration'
inputs:
  test-reports-path:
    description: 'Path to JUnit test reports'
    required: false
    default: 'microservice-moc-app/target/surefire-reports'
  coverage-reports-path:
    description: 'Path to JaCoCo coverage reports'
    required: false
    default: 'microservice-moc-app/target/site/jacoco'
  coverage-threshold:
    description: 'Minimum coverage threshold percentage'
    required: false
    default: '50'
  project-path:
    description: 'Path to the project root'
    required: false
    default: 'microservice-moc-app'

outputs:
  tests-passed:
    description: 'Whether all tests passed'
    value: ${{ steps.test_analysis.outputs.TESTS_PASSED }}
  tests-total:
    description: 'Total number of tests executed'
    value: ${{ steps.test_analysis.outputs.TESTS_TOTAL }}
  tests-failed:
    description: 'Number of failed tests'
    value: ${{ steps.test_analysis.outputs.TESTS_FAILED }}
  tests-skipped:
    description: 'Number of skipped tests'
    value: ${{ steps.test_analysis.outputs.TESTS_SKIPPED }}
  coverage-percent:
    description: 'Code coverage percentage'
    value: ${{ steps.coverage_analysis.outputs.COVERAGE_PERCENT }}
  coverage-lines-covered:
    description: 'Number of lines covered'
    value: ${{ steps.coverage_analysis.outputs.LINES_COVERED }}
  coverage-lines-total:
    description: 'Total number of lines'
    value: ${{ steps.coverage_analysis.outputs.LINES_TOTAL }}
  coverage-threshold-met:
    description: 'Whether coverage threshold was met'
    value: ${{ steps.coverage_analysis.outputs.THRESHOLD_MET }}
  test-artifacts-ready:
    description: 'Whether test artifacts are ready for quality tools'
    value: ${{ steps.artifact_preparation.outputs.ARTIFACTS_READY }}

runs:
  using: 'composite'
  steps:
    - name: Verify test report structure
      shell: bash
      run: |
        echo "📊 Verifying test report structure..."
        echo "Test reports path: ${{ inputs.test-reports-path }}"
        echo "Coverage reports path: ${{ inputs.coverage-reports-path }}"
        
        # Check test reports
        if [ -d "${{ inputs.test-reports-path }}" ]; then
          echo "✅ JUnit test reports directory found"
          echo "📋 Test report files:"
          find "${{ inputs.test-reports-path }}" -name "*.xml" | head -10
        else
          echo "⚠️ JUnit test reports directory not found"
        fi
        
        # Check coverage reports
        if [ -d "${{ inputs.coverage-reports-path }}" ]; then
          echo "✅ JaCoCo coverage reports directory found"
          echo "📋 Coverage report files:"
          ls -la "${{ inputs.coverage-reports-path }}"
        else
          echo "⚠️ JaCoCo coverage reports directory not found"
        fi

    - name: Analyze test results
      id: test_analysis
      shell: bash
      run: |
        echo "🧪 Analyzing JUnit test results..."
        
        TESTS_TOTAL=0
        TESTS_FAILED=0
        TESTS_SKIPPED=0
        TESTS_PASSED="true"
        
        # Parse JUnit XML reports
        if [ -d "${{ inputs.test-reports-path }}" ]; then
          for xml_file in "${{ inputs.test-reports-path }}"/*.xml; do
            if [ -f "$xml_file" ]; then
              echo "📄 Processing: $(basename "$xml_file")"
              
              # Extract test counts using grep and basic parsing
              if command -v grep &> /dev/null; then
                # Extract tests, failures, and skipped from testsuite element
                SUITE_TESTS=$(grep -o 'tests="[0-9]*"' "$xml_file" | grep -o '[0-9]*' | head -1 || echo "0")
                SUITE_FAILURES=$(grep -o 'failures="[0-9]*"' "$xml_file" | grep -o '[0-9]*' | head -1 || echo "0")
                SUITE_SKIPPED=$(grep -o 'skipped="[0-9]*"' "$xml_file" | grep -o '[0-9]*' | head -1 || echo "0")
                
                TESTS_TOTAL=$((TESTS_TOTAL + ${SUITE_TESTS:-0}))
                TESTS_FAILED=$((TESTS_FAILED + ${SUITE_FAILURES:-0}))
                TESTS_SKIPPED=$((TESTS_SKIPPED + ${SUITE_SKIPPED:-0}))
                
                echo "   Tests: ${SUITE_TESTS:-0}, Failures: ${SUITE_FAILURES:-0}, Skipped: ${SUITE_SKIPPED:-0}"
              fi
            fi
          done
        else
          echo "⚠️ No test reports found - assuming no tests were executed"
        fi
        
        # Determine if tests passed
        if [ "$TESTS_FAILED" -gt 0 ]; then
          TESTS_PASSED="false"
          echo "❌ Tests failed: $TESTS_FAILED out of $TESTS_TOTAL tests"
        elif [ "$TESTS_TOTAL" -eq 0 ]; then
          echo "⚠️ No tests executed"
          TESTS_PASSED="false"
        else
          echo "✅ All tests passed: $TESTS_TOTAL tests executed successfully"
        fi
        
        # Set outputs
        echo "TESTS_PASSED=$TESTS_PASSED" >> $GITHUB_OUTPUT
        echo "TESTS_TOTAL=$TESTS_TOTAL" >> $GITHUB_OUTPUT
        echo "TESTS_FAILED=$TESTS_FAILED" >> $GITHUB_OUTPUT
        echo "TESTS_SKIPPED=$TESTS_SKIPPED" >> $GITHUB_OUTPUT

    - name: Analyze coverage results
      id: coverage_analysis
      shell: bash
      run: |
        echo "📊 Analyzing JaCoCo coverage results..."
        
        COVERAGE_PERCENT=0
        LINES_COVERED=0
        LINES_TOTAL=0
        THRESHOLD_MET="false"
        
        JACOCO_XML="${{ inputs.coverage-reports-path }}/jacoco.xml"
        
        if [ -f "$JACOCO_XML" ]; then
          echo "✅ JaCoCo XML report found: $JACOCO_XML"
          
          # Extract coverage statistics using grep and awk
          if command -v grep &> /dev/null && command -v awk &> /dev/null; then
            # Sum all covered and missed lines from all <counter type="LINE"> elements
            LINES_COVERED=$(grep -o '<counter type="LINE"[^>]*covered="[0-9]*"' "$JACOCO_XML" | \
              grep -o 'covered="[0-9]*"' | grep -o '[0-9]*' | \
              awk '{sum += $1} END {print sum+0}')
            
            LINES_MISSED=$(grep -o '<counter type="LINE"[^>]*missed="[0-9]*"' "$JACOCO_XML" | \
              grep -o 'missed="[0-9]*"' | grep -o '[0-9]*' | \
              awk '{sum += $1} END {print sum+0}')
            
            LINES_TOTAL=$((LINES_COVERED + LINES_MISSED))
            
            if [ "$LINES_TOTAL" -gt 0 ]; then
              COVERAGE_PERCENT=$((LINES_COVERED * 100 / LINES_TOTAL))
              
              # Check threshold
              if [ "$COVERAGE_PERCENT" -ge "${{ inputs.coverage-threshold }}" ]; then
                THRESHOLD_MET="true"
                echo "✅ Coverage threshold met: ${COVERAGE_PERCENT}% >= ${{ inputs.coverage-threshold }}%"
              else
                echo "⚠️ Coverage threshold not met: ${COVERAGE_PERCENT}% < ${{ inputs.coverage-threshold }}%"
              fi
              
              echo "📊 Coverage Analysis Results:"
              echo "   Lines Covered: $LINES_COVERED"
              echo "   Lines Total: $LINES_TOTAL" 
              echo "   Coverage: ${COVERAGE_PERCENT}%"
            else
              echo "⚠️ No coverage data found in JaCoCo report"
            fi
          else
            echo "⚠️ grep or awk not available - cannot extract coverage statistics"
          fi
        else
          echo "⚠️ JaCoCo XML report not found: $JACOCO_XML"
          echo "💡 Ensure JaCoCo is configured and mvn test jacoco:report was executed"
        fi
        
        # Set outputs
        echo "COVERAGE_PERCENT=$COVERAGE_PERCENT" >> $GITHUB_OUTPUT
        echo "LINES_COVERED=$LINES_COVERED" >> $GITHUB_OUTPUT
        echo "LINES_TOTAL=$LINES_TOTAL" >> $GITHUB_OUTPUT
        echo "THRESHOLD_MET=$THRESHOLD_MET" >> $GITHUB_OUTPUT

    - name: Prepare artifacts for quality tools
      id: artifact_preparation
      shell: bash
      run: |
        echo "📦 Preparing test artifacts for quality analysis integration..."
        
        ARTIFACTS_READY="false"
        
        # Create standardized results directory
        mkdir -p test-results/junit
        mkdir -p test-results/jacoco
        mkdir -p test-results/summary
        
        # Copy JUnit reports if available
        if [ -d "${{ inputs.test-reports-path }}" ] && [ "$(ls -A ${{ inputs.test-reports-path }}/*.xml 2>/dev/null)" ]; then
          cp "${{ inputs.test-reports-path }}"/*.xml test-results/junit/
          echo "✅ JUnit reports copied to test-results/junit/"
          JUNIT_READY="true"
        else
          echo "⚠️ No JUnit reports to copy"
          JUNIT_READY="false"
        fi
        
        # Copy JaCoCo reports if available
        if [ -d "${{ inputs.coverage-reports-path }}" ]; then
          cp -r "${{ inputs.coverage-reports-path }}"/* test-results/jacoco/ 2>/dev/null || true
          if [ -f "test-results/jacoco/jacoco.xml" ]; then
            echo "✅ JaCoCo reports copied to test-results/jacoco/"
            JACOCO_READY="true"
          else
            echo "⚠️ JaCoCo XML report not found after copy"
            JACOCO_READY="false"
          fi
        else
          echo "⚠️ No JaCoCo reports to copy"
          JACOCO_READY="false"
        fi
        
        # Create test summary JSON for quality tools
        cat > test-results/summary/test-summary.json << EOF
        {
          "timestamp": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
          "test_results": {
            "total_tests": ${{ steps.test_analysis.outputs.TESTS_TOTAL }},
            "failed_tests": ${{ steps.test_analysis.outputs.TESTS_FAILED }},
            "skipped_tests": ${{ steps.test_analysis.outputs.TESTS_SKIPPED }},
            "passed": ${{ steps.test_analysis.outputs.TESTS_PASSED }}
          },
          "coverage_results": {
            "coverage_percent": ${{ steps.coverage_analysis.outputs.COVERAGE_PERCENT }},
            "lines_covered": ${{ steps.coverage_analysis.outputs.LINES_COVERED }},
            "lines_total": ${{ steps.coverage_analysis.outputs.LINES_TOTAL }},
            "threshold_met": ${{ steps.coverage_analysis.outputs.THRESHOLD_MET }},
            "threshold": ${{ inputs.coverage-threshold }}
          },
          "artifacts": {
            "junit_reports": $JUNIT_READY,
            "jacoco_reports": $JACOCO_READY
          }
        }
        EOF
        
        echo "✅ Test summary JSON created"
        
        # Determine overall artifact readiness
        if [ "$JUNIT_READY" = "true" ] || [ "$JACOCO_READY" = "true" ]; then
          ARTIFACTS_READY="true"
          echo "✅ Test artifacts prepared for quality analysis tools"
        else
          echo "⚠️ No test artifacts available for quality tools"
        fi
        
        # Show final structure
        echo "📋 Final test artifacts structure:"
        find test-results -type f | sort
        
        echo "ARTIFACTS_READY=$ARTIFACTS_READY" >> $GITHUB_OUTPUT

    - name: Generate test results summary
      shell: bash
      run: |
        echo "📊 Generating test results summary..."
        
        # Add to GitHub Step Summary
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "## 🧪 Unit Test Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        # Test Results Table
        echo "### 📋 Test Execution Summary" >> $GITHUB_STEP_SUMMARY
        echo "| Metric | Value |" >> $GITHUB_STEP_SUMMARY
        echo "|--------|-------|" >> $GITHUB_STEP_SUMMARY
        echo "| ✅ Tests Passed | ${{ steps.test_analysis.outputs.TESTS_PASSED }} |" >> $GITHUB_STEP_SUMMARY
        echo "| 📊 Total Tests | ${{ steps.test_analysis.outputs.TESTS_TOTAL }} |" >> $GITHUB_STEP_SUMMARY
        echo "| ❌ Failed Tests | ${{ steps.test_analysis.outputs.TESTS_FAILED }} |" >> $GITHUB_STEP_SUMMARY
        echo "| ⏭️ Skipped Tests | ${{ steps.test_analysis.outputs.TESTS_SKIPPED }} |" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        # Coverage Results Table
        echo "### 📊 Code Coverage Analysis" >> $GITHUB_STEP_SUMMARY
        echo "| Metric | Value |" >> $GITHUB_STEP_SUMMARY
        echo "|--------|-------|" >> $GITHUB_STEP_SUMMARY
        echo "| 📈 Coverage Percentage | ${{ steps.coverage_analysis.outputs.COVERAGE_PERCENT }}% |" >> $GITHUB_STEP_SUMMARY
        echo "| ✅ Lines Covered | ${{ steps.coverage_analysis.outputs.LINES_COVERED }} |" >> $GITHUB_STEP_SUMMARY
        echo "| 📏 Total Lines | ${{ steps.coverage_analysis.outputs.LINES_TOTAL }} |" >> $GITHUB_STEP_SUMMARY
        echo "| 🎯 Threshold (${{ inputs.coverage-threshold }}%) | ${{ steps.coverage_analysis.outputs.THRESHOLD_MET }} |" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        # Quality Tools Integration Status
        echo "### 🔗 Quality Tools Integration" >> $GITHUB_STEP_SUMMARY
        echo "| Tool | Status | Artifacts Available |" >> $GITHUB_STEP_SUMMARY
        echo "|------|--------|---------------------|" >> $GITHUB_STEP_SUMMARY
        
        if [ -f "test-results/jacoco/jacoco.xml" ]; then
          echo "| 🔍 SonarQube | ✅ Ready | JaCoCo XML, JUnit reports |" >> $GITHUB_STEP_SUMMARY
          echo "| 📊 Codacy | ✅ Ready | Coverage data, Test results |" >> $GITHUB_STEP_SUMMARY
        else
          echo "| 🔍 SonarQube | ⚠️ Limited | JUnit reports only |" >> $GITHUB_STEP_SUMMARY
          echo "| 📊 Codacy | ⚠️ Limited | Test results only |" >> $GITHUB_STEP_SUMMARY
        fi
        
        echo "| 🧪 Test Artifacts | ${{ steps.artifact_preparation.outputs.ARTIFACTS_READY }} | Standard format prepared |" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        # Add status indicator
        if [ "${{ steps.test_analysis.outputs.TESTS_PASSED }}" = "true" ] && [ "${{ steps.coverage_analysis.outputs.THRESHOLD_MET }}" = "true" ]; then
          echo "### ✅ Unit Test Status: **PASSED**" >> $GITHUB_STEP_SUMMARY
          echo "All tests passed and coverage threshold met. Ready for quality analysis." >> $GITHUB_STEP_SUMMARY
        elif [ "${{ steps.test_analysis.outputs.TESTS_PASSED }}" = "true" ]; then
          echo "### ⚠️ Unit Test Status: **PASSED WITH WARNINGS**" >> $GITHUB_STEP_SUMMARY
          echo "Tests passed but coverage threshold not met. Consider adding more tests." >> $GITHUB_STEP_SUMMARY
        else
          echo "### ❌ Unit Test Status: **FAILED**" >> $GITHUB_STEP_SUMMARY
          echo "Some tests failed. Review test results and fix failing tests before deployment." >> $GITHUB_STEP_SUMMARY
        fi