name: 'Process Security Artifacts'
description: 'Processes and validates security scan artifacts from Snyk, SonarQube, Codacy, and test results'

inputs:
  process-snyk:
    description: 'Process Snyk artifacts'
    required: false
    default: 'true'
  process-sonarqube:
    description: 'Process SonarQube artifacts'
    required: false
    default: 'true'
  process-codacy:
    description: 'Process Codacy artifacts'
    required: false
    default: 'true'
  process-tests:
    description: 'Process test result artifacts'
    required: false
    default: 'true'

outputs:
  artifacts-count:
    description: 'Total number of artifacts processed'
    value: ${{ steps.process-artifacts.outputs.artifacts-count }}
  snyk-results-path:
    description: 'Path to Snyk results file'
    value: ${{ steps.process-artifacts.outputs.snyk-results-path }}
  sonarqube-results-path:
    description: 'Path to SonarQube results file'
    value: ${{ steps.process-artifacts.outputs.sonarqube-results-path }}
  codacy-results-path:
    description: 'Path to Codacy results file'
    value: ${{ steps.process-artifacts.outputs.codacy-results-path }}
  test-results-path:
    description: 'Path to test results file'
    value: ${{ steps.process-artifacts.outputs.test-results-path }}
  artifact-locations:
    description: 'JSON summary of all artifact locations'
    value: ${{ steps.process-artifacts.outputs.artifact-locations }}

runs:
  using: 'composite'
  steps:
    - name: Install jq for JSON processing
      shell: bash
      run: |
        if ! command -v jq &> /dev/null; then
          sudo apt-get update -qq
          sudo apt-get install -y jq
        fi
        
    - name: Process Security Artifacts
      id: process-artifacts
      shell: bash
      run: |
        echo "ðŸ“ Processing security scan artifacts..."
        
        # Initialize directories
        mkdir -p snyk-scanning/results sonarqube-cloud-scanning/results codacy-scanning/results test-results/processed
        
        ARTIFACTS_PROCESSED=0
        # Initialize individual path variables
        SNYK_RESULTS_PATH=""
        SONARQUBE_RESULTS_PATH=""
        CODACY_RESULTS_PATH=""
        TEST_RESULTS_PATH=""
        
        # Process Snyk artifacts
        if [ "${{ inputs.process-snyk }}" = "true" ]; then
          echo "ðŸ” Processing Snyk artifacts..."
          
          # Process Snyk vulnerability results
          if [ -f "snyk-results.json" ]; then
            if jq empty snyk-results.json 2>/dev/null; then
              mv snyk-results.json snyk-scanning/results/
              echo "âœ… Snyk vulnerability scan results processed"
              ARTIFACTS_PROCESSED=$((ARTIFACTS_PROCESSED + 1))
              SNYK_RESULTS_PATH="snyk-scanning/results/snyk-results.json"
            else
              echo "âš ï¸ Invalid JSON in snyk-results.json - skipping"
            fi
          else
            echo "â„¹ï¸ snyk-results.json not found"
          fi
          
          # Process Snyk code analysis results
          if [ -f "snyk-code-results.json" ]; then
            if jq empty snyk-code-results.json 2>/dev/null; then
              mv snyk-code-results.json snyk-scanning/results/
              echo "âœ… Snyk code analysis results processed"
              ARTIFACTS_PROCESSED=$((ARTIFACTS_PROCESSED + 1))
            else
              echo "âš ï¸ Invalid JSON in snyk-code-results.json - skipping"
            fi
          else
            echo "â„¹ï¸ snyk-code-results.json not found"
          fi
          
          # Process Snyk container results
          if [ -f "snyk-container-results.json" ]; then
            if jq empty snyk-container-results.json 2>/dev/null; then
              mv snyk-container-results.json snyk-scanning/results/
              echo "âœ… Snyk container scan results processed"
              ARTIFACTS_PROCESSED=$((ARTIFACTS_PROCESSED + 1))
            else
              echo "âš ï¸ Invalid JSON in snyk-container-results.json - skipping"
            fi
          else
            echo "â„¹ï¸ snyk-container-results.json not found"
          fi
          
          echo "snyk-results-path=$SNYK_RESULTS_PATH" >> $GITHUB_OUTPUT
        fi
        
        # Process SonarQube artifacts
        if [ "${{ inputs.process-sonarqube }}" = "true" ]; then
          echo "ðŸ” Processing SonarQube artifacts..."
          
          if [ -f "quality-gate-result.json" ]; then
            if jq empty quality-gate-result.json 2>/dev/null; then
              # Check if it's SonarQube result (not Codacy)
              if ! jq -e '.tool == "codacy"' quality-gate-result.json >/dev/null 2>&1; then
                mv quality-gate-result.json sonarqube-cloud-scanning/results/
                echo "âœ… SonarQube quality gate results processed"
                ARTIFACTS_PROCESSED=$((ARTIFACTS_PROCESSED + 1))
                SONARQUBE_RESULTS_PATH="sonarqube-cloud-scanning/results/quality-gate-result.json"
              fi
            else
              echo "âš ï¸ Invalid JSON in quality-gate-result.json - skipping"
            fi
          else
            echo "â„¹ï¸ quality-gate-result.json not found"
          fi
          
          echo "sonarqube-results-path=$SONARQUBE_RESULTS_PATH" >> $GITHUB_OUTPUT
        fi
        
        # Process Codacy artifacts
        if [ "${{ inputs.process-codacy }}" = "true" ]; then
          echo "ðŸ” Processing Codacy artifacts..."
          
          # Process SARIF results
          if [ -f "codacy-analysis.sarif" ]; then
            if jq empty codacy-analysis.sarif 2>/dev/null; then
              mv codacy-analysis.sarif codacy-scanning/results/
              echo "âœ… Codacy analysis SARIF results processed"
              ARTIFACTS_PROCESSED=$((ARTIFACTS_PROCESSED + 1))
            else
              echo "âš ï¸ Invalid JSON in codacy-analysis.sarif - skipping"
            fi
          else
            echo "â„¹ï¸ codacy-analysis.sarif not found"
          fi
          
          # Process analysis summary
          if [ -f "analysis-summary.json" ]; then
            if jq empty analysis-summary.json 2>/dev/null; then
              mv analysis-summary.json codacy-scanning/results/
              echo "âœ… Codacy analysis summary processed"
              ARTIFACTS_PROCESSED=$((ARTIFACTS_PROCESSED + 1))
            else
              echo "âš ï¸ Invalid JSON in analysis-summary.json - skipping"
            fi
          else
            echo "â„¹ï¸ analysis-summary.json not found"
          fi
          
          # Process Codacy quality gate result
          if [ -f "codacy-scanning/results/quality-gate-result.json" ]; then
            echo "âœ… Codacy quality gate results already in place"
            ARTIFACTS_PROCESSED=$((ARTIFACTS_PROCESSED + 1))
            CODACY_RESULTS_PATH="codacy-scanning/results/quality-gate-result.json"
          elif [ -f "quality-gate-result.json" ]; then
            if jq empty quality-gate-result.json 2>/dev/null; then
              # Check if it's Codacy result
              if jq -e '.tool == "codacy"' quality-gate-result.json >/dev/null 2>&1; then
                mv quality-gate-result.json codacy-scanning/results/
                echo "âœ… Codacy quality gate results processed"
                ARTIFACTS_PROCESSED=$((ARTIFACTS_PROCESSED + 1))
                CODACY_RESULTS_PATH="codacy-scanning/results/quality-gate-result.json"
              fi
            fi
          fi
          
          echo "codacy-results-path=$CODACY_RESULTS_PATH" >> $GITHUB_OUTPUT
        fi
        
        # Process test results
        if [ "${{ inputs.process-tests }}" = "true" ]; then
          echo "ðŸ” Processing test result artifacts..."
          
          # Process test summary
          if [ -f "test-results/summary/test-summary.json" ]; then
            if jq empty test-results/summary/test-summary.json 2>/dev/null; then
              cp test-results/summary/test-summary.json test-results/processed/
              echo "âœ… Unit test summary processed"
              ARTIFACTS_PROCESSED=$((ARTIFACTS_PROCESSED + 1))
              TEST_RESULTS_PATH="test-results/processed/test-summary.json"
            else
              echo "âš ï¸ Invalid JSON in test-summary.json - skipping"
            fi
          else
            echo "â„¹ï¸ test-summary.json not found"
          fi
          
          # Process JUnit test reports
          if [ -d "test-results/junit" ] && [ "$(ls -A test-results/junit/*.xml 2>/dev/null)" ]; then
            echo "âœ… JUnit test reports processed ($(ls test-results/junit/*.xml | wc -l) files)"
            ARTIFACTS_PROCESSED=$((ARTIFACTS_PROCESSED + 1))
          else
            echo "â„¹ï¸ JUnit test reports not found"
          fi
          
          # Process JaCoCo coverage reports
          if [ -f "test-results/jacoco/jacoco.xml" ]; then
            echo "âœ… JaCoCo coverage report processed"
            ARTIFACTS_PROCESSED=$((ARTIFACTS_PROCESSED + 1))
          else
            echo "â„¹ï¸ JaCoCo coverage report not found"
          fi
          
          echo "test-results-path=$TEST_RESULTS_PATH" >> $GITHUB_OUTPUT
        fi
        
        echo "ðŸ“Š Summary: Processed $ARTIFACTS_PROCESSED artifact(s)"
        echo "artifacts-count=$ARTIFACTS_PROCESSED" >> $GITHUB_OUTPUT
        
        # Create properly formatted JSON for artifact locations using jq
        ARTIFACT_LOCATIONS=$(jq -cn \
          --arg snyk "$SNYK_RESULTS_PATH" \
          --arg sonarqube "$SONARQUBE_RESULTS_PATH" \
          --arg codacy "$CODACY_RESULTS_PATH" \
          --arg tests "$TEST_RESULTS_PATH" \
          '{snyk: $snyk, sonarqube: $sonarqube, codacy: $codacy, tests: $tests}')
        
        # Debug: Show generated JSON structure
        echo "ðŸ” Generated JSON: $ARTIFACT_LOCATIONS"
        echo "ðŸ” JSON length: ${#ARTIFACT_LOCATIONS} characters"
        
        # Validate and output JSON
        if echo "$ARTIFACT_LOCATIONS" | jq empty 2>/dev/null; then
          echo "artifact-locations=$ARTIFACT_LOCATIONS" >> $GITHUB_OUTPUT
          echo "âœ… Artifact locations JSON created successfully (single-line compact format)"
        else
          echo "âš ï¸ Failed to create artifact locations JSON, using empty object"
          echo "ðŸ” JSON validation error: $(echo "$ARTIFACT_LOCATIONS" | jq empty 2>&1 || true)"
          echo "artifact-locations={}" >> $GITHUB_OUTPUT
        fi
        
        # Show final directory structure
        echo "ðŸ“‹ Final artifact locations:"
        find snyk-scanning sonarqube-cloud-scanning codacy-scanning test-results \
          -name "*.json" -o -name "*.sarif" -o -name "*.xml" 2>/dev/null | head -20 || echo "No artifacts found"