name: "Sonar Scan"
description: "Run SonarCloud scan and validate quality gate"

inputs:
  app-path:
    description: 'Path of the project to scan'
    required: true
  sonar-host-url:
    description: 'url of the SonarCloud server'
    required: true
  tech-version:
    description: 'Node.js version to use'
    required: true
  project-path:
    description: 'Path to the Node.js project'
    required: true
  sonar-token:
    description: 'SonarCloud token'
    required: true
  sonar-organization:
    description: 'SonarCloud organization key'
    required: true
  sonar-project-key:
    description: 'SonarCloud project key'
    required: true
  sonar-branch:
    description: 'Branch name for the Sonar scan'
    required: false
  app-techstack:
    description: ''
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Java and Sonar Scanner
      shell: bash
      run: |
        apt-get update  -qq > /dev/null
        apt-get install -y openjdk-17-jre python3  > /dev/null
        npm install -g sonar-scanner --silent > /dev/null

    
    - name: Sonar Env Info
      shell: bash
      run: |
        echo "Sonar Scan Configuration:"
        echo "App Path: ${{ inputs.app-path }}"
        echo "Sonar Host URL: ${{ inputs.sonar-host-url }}"

        if [[ "${{ inputs.app-techstack }}" == "java" ]]; then
            echo "Java version: ${{ inputs.tech-version }}"
        fi

        if [[ "${{ inputs.app-techstack }}" == "nodejs" ]]; then
            echo "Node Version: ${{ inputs.tech-version }}"
        fi
        
        echo "Project Path: ${{ inputs.project-path }}"
        echo "Sonar Organization: ${{ inputs.sonar-organization }}"
        echo "Sonar Project Key: ${{ inputs.sonar-project-key }}"
    
    # - name: Generate sonar-project.properties
    #   shell: bash
    #   run: |
    #     cd ${{ inputs.app-path }}
    #     cat <<EOF > sonar-project.properties
    #     sonar.projectKey=${{ inputs.sonar-project-key }}
    #     sonar.organization=${{ inputs.sonar-organization }}
    #     sonar.sources=src,helm,Dockerfile
    #     sonar.tests=src
    #     sonar.test.inclusions=**/__tests__/**/*.js
    #     sonar.javascript.lcov.reportPaths=coverage/lcov.info
    #     sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**
    #     sonar.sourceEncoding=UTF-8
    #     EOF
      #-Dsonar.projectVersion=1.0.0 \

    - name: Detect Project Tech Stack
      shell: bash
      run:  |
          cd "${{ inputs.app-path }}"
          python3 scripts/sonar-tech.py

    - name: Generate Properties
      shell: bash
      run: |
        cd "${{ inputs.app-path }}"

        echo "Generating properties using: $SONAR_PROPS"

        > sonar-project.properties

        IFS=',' read -ra FILES <<< "$SONAR_PROPS"
        for f in "${FILES[@]}"; do
          echo "Adding $f"
          cat "$f" >> sonar-project.properties
          echo "" >> sonar-project.properties
        done

        echo "Project Pproperties:"
        cat sonar-project.properties

    - name: Sonar Scan
      env:
        SONAR_TOKEN: ${{ inputs.sonar-token }}
      shell: bash
      continue-on-error: true
      run: |
        cd ${{ inputs.app-path }}
        sonar-scanner \
          -Dsonar.host.url=${{ inputs.sonar-host-url }} \
          -Dsonar.login=${{ inputs.sonar-token }} \
          -Dsonar.qualitygate.wait=true \
          -Dsonar.qualitygate.timeout=300 &> /dev/null || SONAR_EXIT_CODE=$? 

    # - name: Check Quality Gate
    #   shell: bash
    #   env:
    #     SONAR_TOKEN: ${{ inputs.sonar-token }}
    #   run: |
    #     cd ${{ inputs.app-path }}
    #     STATUS=$(curl -s -u $SONAR_TOKEN: \
    #       "${{ inputs.sonar-host-url }}/api/qualitygates/project_status?projectKey=poc-pipeline_multi-stack-project-hub" \
    #       | grep -o '"status":"[^"]*"' | cut -d'"' -f4)
    #     echo "Sonar status: $STATUS"
    #     if [ "$STATUS" = "ERROR" ]; then
    #       echo "::error::Quality Gate failed"
    #       exit 1
    #     fi
