name: 'Evaluate Permit Gates'
description: 'Wrapper for permit-gating/scripts/evaluate-gates.sh with enhanced output handling'

inputs:
  snyk-results-path:
    description: 'Path to Snyk results JSON file'
    required: false
    default: 'snyk-scanning/results/snyk-results.json'
  pdp-url:
    description: 'PDP URL for authorization requests'
    required: false
    default: 'http://localhost:7766'
  permit-api-key:
    description: 'Permit.io API key'
    required: true
  user-key:
    description: 'User key (GitHub username)'
    required: true
  user-role:
    description: 'User role for authorization'
    required: true
  access-level:
    description: 'Access level based on role'
    required: true
  debug-mode:
    description: 'Enable debug mode for detailed logging'
    required: false
    default: 'false'

outputs:
  gate-result:
    description: 'Gate evaluation result (0=pass, 1=warning, 2=blocked)'
    value: ${{ steps.evaluate-gates.outputs.gate-result }}
  critical-count:
    description: 'Number of critical vulnerabilities found'
    value: ${{ steps.evaluate-gates.outputs.critical-count }}
  high-count:
    description: 'Number of high vulnerabilities found'
    value: ${{ steps.evaluate-gates.outputs.high-count }}
  medium-count:
    description: 'Number of medium vulnerabilities found'
    value: ${{ steps.evaluate-gates.outputs.medium-count }}
  low-count:
    description: 'Number of low vulnerabilities found'
    value: ${{ steps.evaluate-gates.outputs.low-count }}
  decision-reason:
    description: 'Human-readable reason for the gate decision'
    value: ${{ steps.evaluate-gates.outputs.decision-reason }}

runs:
  using: 'composite'
  steps:
    - name: Make scripts executable
      shell: bash
      run: |
        chmod +x permit-gating/scripts/evaluate-gates.sh
        
    - name: Evaluate Safe Deployment Gate
      id: evaluate-gates
      shell: bash
      env:
        PDP_URL: ${{ inputs.pdp-url }}
        PERMIT_API_KEY: ${{ inputs.permit-api-key }}
        USER_KEY: ${{ inputs.user-key }}
        USER_ROLE: ${{ inputs.user-role }}
        ACCESS_LEVEL: ${{ inputs.access-level }}
        DEBUG: ${{ inputs.debug-mode }}
      run: |
        echo "🚪 Safe Deployment Gate Evaluation (Inverted ABAC Logic):"
        echo "  👤 GitHub User: ${USER_KEY}"
        echo "  🎭 Permit.io Role: ${USER_ROLE}"
        echo "  🔐 Access Level: ${ACCESS_LEVEL}"
        echo "  🔄 Logic: Resource Set matches when criticalCount = 0"
        echo "  📊 Architecture: PDP-only (no OPAL services needed)"
        echo ""
        
        # Initialize counts
        CRITICAL_COUNT=0
        HIGH_COUNT=0
        MEDIUM_COUNT=0
        LOW_COUNT=0
        
        # Extract vulnerability counts from Snyk results if available
        if [ -f "${{ inputs.snyk-results-path }}" ]; then
          CRITICAL_COUNT=$(jq '.vulnerabilities | map(select(.severity == "critical")) | length // 0' "${{ inputs.snyk-results-path }}" 2>/dev/null || echo "0")
          HIGH_COUNT=$(jq '.vulnerabilities | map(select(.severity == "high")) | length // 0' "${{ inputs.snyk-results-path }}" 2>/dev/null || echo "0")
          MEDIUM_COUNT=$(jq '.vulnerabilities | map(select(.severity == "medium")) | length // 0' "${{ inputs.snyk-results-path }}" 2>/dev/null || echo "0")
          LOW_COUNT=$(jq '.vulnerabilities | map(select(.severity == "low")) | length // 0' "${{ inputs.snyk-results-path }}" 2>/dev/null || echo "0")
        fi
        
        # Run Safe Deployment Gate evaluation
        echo "Evaluating Safe Deployment Gate with Resource Set matching..."
        
        # Disable exit on error temporarily to capture exit code
        set +e
        ./permit-gating/scripts/evaluate-gates.sh "${{ inputs.snyk-results-path }}"
        SECURITY_GATE_RESULT=$?
        set -e
        
        # Determine decision reason based on result and access level
        DECISION_REASON=""
        case $SECURITY_GATE_RESULT in
          0)
            case "$ACCESS_LEVEL" in
              "SAFE_ONLY")
                DECISION_REASON="Safe deployment authorized - no critical vulnerabilities"
                echo "✅ Safe Deployment Gate: MATCHED (criticalCount = 0)"
                echo "   🟢 Result: Safe deployment authorized for $USER_ROLE"
                echo "   📋 Resource Set: 'Safe Deployment Gate' condition satisfied"
                ;;
              "EMERGENCY_OVERRIDE"|"FULL_OVERRIDE")
                if [ "$CRITICAL_COUNT" -gt 0 ]; then
                  DECISION_REASON="Critical vulnerabilities ($CRITICAL_COUNT) overridden by $USER_ROLE"
                  echo "🔓 Safe Deployment Gate: OVERRIDE ACTIVE"
                  echo "   🟡 Result: Critical vulnerabilities ($CRITICAL_COUNT) overridden by $USER_ROLE"
                  echo "   📋 Resource: Base deployment accessed with override permission"
                else
                  DECISION_REASON="Safe deployment authorized - no critical vulnerabilities"
                  echo "✅ Safe Deployment Gate: MATCHED (criticalCount = 0)"
                  echo "   🟢 Result: Safe deployment authorized for $USER_ROLE"
                  echo "   📋 Resource Set: 'Safe Deployment Gate' condition satisfied"
                fi
                ;;
            esac
            ;;
          1)
            DECISION_REASON="Non-blocking security warnings present"
            echo "⚠️ Safe Deployment Gate: WARNING"
            echo "   🟡 High/medium vulnerabilities present but non-blocking"
            echo "   📋 Deployment proceeding with warnings"
            ;;
          2)
            DECISION_REASON="Blocked - $CRITICAL_COUNT critical vulnerabilities, role '$USER_ROLE' cannot override"
            echo "❌ Safe Deployment Gate: BLOCKED"
            echo "   🔴 Critical vulnerabilities present: $CRITICAL_COUNT"
            echo "   🚫 User role '$USER_ROLE' cannot access base deployment resource"
            echo "   📋 Resource Set: 'Safe Deployment Gate' condition NOT met (criticalCount > 0)"
            echo "   💡 Solutions:"
            echo "      • Fix critical vulnerabilities to enable Safe Deployment Gate"
            echo "      • Use editor or Security Officer role for emergency override"
            ;;
          *)
            DECISION_REASON="Gate evaluation error - check configuration"
            echo "❓ Safe Deployment Gate: ERROR"
            echo "   🚨 Unexpected gate result: $SECURITY_GATE_RESULT"
            ;;
        esac
        
        # Determine gate status and comprehensive details based on result
        GATE_STATUS=""
        GATE_DETAILS=""
        
        case $SECURITY_GATE_RESULT in
          0)
            if [ "$CRITICAL_COUNT" -gt 0 ] && [[ "$ACCESS_LEVEL" == *"OVERRIDE" ]]; then
              GATE_STATUS="🔓 OVERRIDE"
              GATE_DETAILS="$CRITICAL_COUNT critical vulnerabilities overridden"
            else
              GATE_STATUS="✅ PASSED"
              GATE_DETAILS="Safe deployment authorized"
            fi
            ;;
          1)
            GATE_STATUS="⚠️ WARNING"
            GATE_DETAILS="Non-critical vulnerabilities detected"
            ;;
          2)
            GATE_STATUS="❌ BLOCKED"
            GATE_DETAILS="Critical vulnerabilities prevent deployment"
            ;;
          *)
            GATE_STATUS="❓ UNKNOWN"
            GATE_DETAILS="Unexpected result code: $SECURITY_GATE_RESULT"
            ;;
        esac
        
        # Set outputs with validation
        echo "gate-result=$SECURITY_GATE_RESULT" >> $GITHUB_OUTPUT
        echo "gate-status=$GATE_STATUS" >> $GITHUB_OUTPUT
        echo "gate-details=$GATE_DETAILS" >> $GITHUB_OUTPUT
        echo "critical-count=$CRITICAL_COUNT" >> $GITHUB_OUTPUT
        echo "high-count=$HIGH_COUNT" >> $GITHUB_OUTPUT
        echo "medium-count=$MEDIUM_COUNT" >> $GITHUB_OUTPUT
        echo "low-count=$LOW_COUNT" >> $GITHUB_OUTPUT
        
        # Ensure decision reason is safe for GitHub Actions output
        SAFE_DECISION_REASON=$(echo "$DECISION_REASON" | tr '\n' ' ' | tr '\r' ' ')
        echo "decision-reason=$SAFE_DECISION_REASON" >> $GITHUB_OUTPUT
        
        # Add role validation information if in debug mode
        if [ "${{ inputs.debug-mode }}" = "true" ]; then
          echo ""
          echo "🔍 Debug Information:"
          echo "   Gate Result Code: $SECURITY_GATE_RESULT"
          echo "   Critical Count: $CRITICAL_COUNT"
          echo "   High Count: $HIGH_COUNT"
          echo "   Medium Count: $MEDIUM_COUNT"
          echo "   Low Count: $LOW_COUNT"
          echo "   Decision: $DECISION_REASON"
        fi
        
        # Exit with the gate result
        exit $SECURITY_GATE_RESULT